# viewer1 → viewer
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: viewer1-binding
subjects:
  - kind: User
    name: viewer1
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: viewer
  apiGroup: rbac.authorization.k8s.io

---
# operator1 → operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator1-binding
subjects:
  - kind: User
    name: operator1
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: operator
  apiGroup: rbac.authorization.k8s.io

